spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/autocazing?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://config-server:8888