server:
  port: 8080

spring:
  application:
    name: autocazing_apigateway
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/