spring:
  application:
    name: inventory-service
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autocazing?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}