spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autocazing?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka