spring:
  application:
    name: inventory-service
  profiles:
    active: ${profile}
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}